local M = {}

local function with_style(spec, style)
  return vim.tbl_extend("force", spec, style or {})
end

local function apply_groups(groups)
  for group, spec in pairs(groups) do
    vim.api.nvim_set_hl(0, group, spec)
  end
end

local function apply_terminal(c)
  -- Map ANSI slots to the base palette and generated bright variants.
  local colors = {
    c.void,
    c.redshift,
    c.blueshift,
    c.corona,
    c.blueshift,
    c.ash,
    c.blueshift,
    c.starlight,
    c.ash,
    c.redshift_bright,
    c.blueshift_bright,
    c.corona_bright,
    c.blueshift_bright,
    c.starlight,
    c.blueshift_bright,
    c.starlight,
  }

  for index, color in ipairs(colors) do
    vim.g["terminal_color_" .. (index - 1)] = color
  end
end

function M.apply(c, config)
  local normal_bg = config.transparent and "NONE" or c.bg
  local styles = config.styles

  local groups = {
    -- Editor chrome ---------------------------------------------------------
    Normal = { fg = c.fg, bg = normal_bg },
    NormalNC = { fg = config.dim_inactive and c.muted or c.fg, bg = normal_bg },
    NormalFloat = { fg = c.fg, bg = c.surface1 },
    FloatBorder = { fg = c.border, bg = c.surface1 },
    FloatTitle = { fg = c.starlight, bg = c.surface1, bold = true },
    FloatFooter = { fg = c.muted, bg = c.surface1 },
    FloatShadow = { bg = c.void, blend = 35 },
    FloatShadowThrough = { bg = c.void, blend = 80 },
    MsgArea = { fg = c.fg, bg = normal_bg },
    MsgSeparator = { fg = c.border, bg = normal_bg },

    Cursor = { fg = c.void, bg = c.starlight },
    lCursor = { fg = c.void, bg = c.starlight },
    CursorIM = { fg = c.void, bg = c.starlight },
    TermCursor = { fg = c.void, bg = c.starlight },
    TermCursorNC = { fg = c.void, bg = c.ash },
    CursorLine = { bg = c.surface0 },
    CursorColumn = { bg = c.surface0 },
    ColorColumn = { bg = c.surface1 },

    LineNr = { fg = c.subtle },
    LineNrAbove = { fg = c.subtle },
    LineNrBelow = { fg = c.subtle },
    CursorLineNr = { fg = c.starlight, bold = true },
    CursorLineSign = { bg = c.surface0 },
    CursorLineFold = { bg = c.surface0 },
    SignColumn = { fg = c.muted, bg = normal_bg },
    FoldColumn = { fg = c.subtle, bg = normal_bg },
    Folded = { fg = c.muted, bg = c.surface0, italic = true },

    WinSeparator = { fg = c.border, bg = normal_bg },
    VertSplit = { fg = c.border, bg = normal_bg },
    WinBar = { fg = c.fg, bg = normal_bg, bold = true },
    WinBarNC = { fg = c.muted, bg = normal_bg },
    StatusLine = { fg = c.fg, bg = c.surface1, bold = true },
    StatusLineNC = { fg = c.muted, bg = c.surface0 },
    StatusLineTerm = { fg = c.fg, bg = c.surface1 },
    StatusLineTermNC = { fg = c.muted, bg = c.surface0 },
    TabLine = { fg = c.muted, bg = c.surface0 },
    TabLineFill = { bg = c.surface0 },
    TabLineSel = { fg = c.void, bg = c.starlight, bold = true },

    Pmenu = { fg = c.fg, bg = c.surface1 },
    PmenuSel = { fg = c.void, bg = c.starlight, bold = true },
    PmenuKind = { fg = c.muted, bg = c.surface1 },
    PmenuKindSel = { fg = c.void, bg = c.starlight },
    PmenuExtra = { fg = c.muted, bg = c.surface1 },
    PmenuExtraSel = { fg = c.void, bg = c.starlight },
    PmenuSbar = { bg = c.surface2 },
    PmenuThumb = { bg = c.border },
    PmenuMatch = { fg = c.corona, bold = true },
    PmenuMatchSel = { fg = c.void, bg = c.starlight, bold = true },
    ComplMatchIns = { fg = c.corona },
    WildMenu = { fg = c.void, bg = c.corona, bold = true },

    Visual = { bg = c.selection },
    VisualNOS = { bg = c.selection },
    Search = { fg = c.void, bg = c.corona, bold = true },
    IncSearch = { fg = c.void, bg = c.starlight, bold = true },
    CurSearch = { fg = c.void, bg = c.starlight, bold = true },
    Substitute = { fg = c.void, bg = c.redshift, bold = true },
    MatchParen = { fg = c.corona, bold = true },
    QuickFixLine = { bg = c.selection, bold = true },
    qfLineNr = { fg = c.muted },

    Directory = { fg = c.starlight, bold = true },
    Title = { fg = c.starlight, bold = true },
    Conceal = { fg = c.muted },
    NonText = { fg = c.subtle },
    EndOfBuffer = { fg = c.subtle },
    SpecialKey = { fg = c.subtle },
    Whitespace = { fg = c.subtle },

    ErrorMsg = { fg = c.redshift, bold = true },
    WarningMsg = { fg = c.corona, bold = true },
    MoreMsg = { fg = c.starlight, bold = true },
    ModeMsg = { fg = c.fg, bold = true },
    Question = { fg = c.starlight, bold = true },

    SpellBad = { undercurl = true, sp = c.redshift },
    SpellCap = { undercurl = true, sp = c.corona },
    SpellLocal = { undercurl = true, sp = c.blueshift },
    SpellRare = { undercurl = true, sp = c.ash },

    -- Diffs use tinted surfaces rather than adding a conventional green.
    DiffAdd = { fg = c.blueshift, bg = c.diff_add },
    DiffChange = { fg = c.corona, bg = c.diff_change },
    DiffDelete = { fg = c.redshift, bg = c.diff_delete },
    DiffText = { fg = c.starlight, bg = c.warm_surface, bold = true },
    Added = { fg = c.blueshift },
    Changed = { fg = c.corona },
    Removed = { fg = c.redshift },

    -- Legacy syntax --------------------------------------------------------
    Bold = { bold = true },
    Italic = { italic = true },
    -- Shared syntax groups used by Tree-sitter and language-specific queries.
    OriginChoice = { fg = c.corona, bold = true, nocombine = true },
    OriginStructure = { fg = c.starlight, bold = true, nocombine = true },
    OriginDefinition = { fg = c.starlight, bold = true, nocombine = true },
    OriginTypeDefinition = { fg = c.starlight, bold = true, nocombine = true },
    OriginFlow = { fg = c.corona, bold = true, nocombine = true },
    OriginMetaType = { fg = c.blueshift, nocombine = true },

    -- Base syntax groups.
    OriginDeclaration = { fg = c.starlight, bold = true },
    OriginCall = with_style({ fg = c.starlight }, styles.functions),
    OriginMeta = { fg = c.ash },
    Comment = with_style({ fg = c.muted }, styles.comments),
    Constant = { fg = c.halo },
    String = with_style({ fg = c.fg }, styles.strings),
    Character = { fg = c.starlight },
    Number = { fg = c.starlight },
    Boolean = { fg = c.starlight },
    Float = { fg = c.starlight },
    Identifier = with_style({ fg = c.fg }, styles.variables),
    -- Legacy syntax cannot distinguish definitions from calls, so keep the
    -- fallback neutral; Treesitter provides the structural distinction.
    Function = with_style({ fg = c.starlight }, styles.functions),
    Statement = with_style({ fg = c.starlight }, styles.keywords),
    Conditional = { link = "OriginChoice" },
    Repeat = { link = "OriginChoice" },
    Label = { link = "OriginChoice" },
    Operator = { fg = c.starlight },
    Keyword = { link = "Statement" },
    Exception = { link = "OriginChoice" },
    PreProc = { link = "OriginMeta" },
    Include = { link = "OriginMeta" },
    Define = { link = "OriginMeta" },
    Macro = { link = "OriginMeta" },
    PreCondit = { link = "OriginMeta" },
    Type = with_style({ fg = c.blueshift, nocombine = true }, styles.types),
    StorageClass = { fg = c.fg, bold = true },
    Structure = { link = "Type" },
    Typedef = { link = "Type" },
    Special = { fg = c.fg, bold = true },
    SpecialChar = { fg = c.fg, bold = true },
    Tag = { fg = c.fg },
    Delimiter = { fg = c.ash },
    SpecialComment = { fg = c.muted, bold = true, italic = true },
    Debug = { fg = c.fg, bold = true },
    Underlined = { fg = c.fg, underline = true },
    Ignore = { fg = c.subtle },
    Error = { fg = c.redshift, bold = true },
    Todo = { fg = c.void, bg = c.starlight, bold = true },

    -- Diagnostics and LSP --------------------------------------------------
    DiagnosticError = { fg = c.redshift },
    DiagnosticWarn = { fg = c.corona },
    DiagnosticInfo = { fg = c.blueshift },
    DiagnosticHint = { fg = c.muted },
    DiagnosticOk = { fg = c.blueshift },
    -- Undercurl supports a severity-specific `sp` color without replacing the
    -- syntax foreground. Plain terminal underlines cannot do this reliably.
    DiagnosticUnderlineError = { undercurl = true, sp = c.redshift },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.corona },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.blueshift },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.ash },
    DiagnosticUnderlineOk = { undercurl = true, sp = c.blueshift },
    DiagnosticVirtualTextError = { fg = c.redshift, bg = c.diff_delete },
    DiagnosticVirtualTextWarn = { fg = c.corona, bg = c.diff_change },
    DiagnosticVirtualTextInfo = { fg = c.blueshift, bg = c.info_surface },
    DiagnosticVirtualTextHint = { fg = c.muted, bg = c.surface0 },
    DiagnosticVirtualTextOk = { fg = c.blueshift, bg = c.success_surface },
    DiagnosticFloatingError = { link = "DiagnosticError" },
    DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
    DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
    DiagnosticFloatingHint = { link = "DiagnosticHint" },
    DiagnosticFloatingOk = { link = "DiagnosticOk" },
    DiagnosticSignError = { fg = c.redshift, bold = true },
    DiagnosticSignWarn = { fg = c.corona, bold = true },
    DiagnosticSignInfo = { fg = c.blueshift },
    DiagnosticSignHint = { fg = c.muted },
    DiagnosticSignOk = { fg = c.blueshift },
    DiagnosticUnnecessary = { fg = c.subtle },
    DiagnosticDeprecated = { strikethrough = true, sp = c.ash },

    LspReferenceText = { bg = c.surface2 },
    LspReferenceRead = { bg = c.surface2 },
    LspReferenceWrite = { bg = c.selection, bold = true },
    LspSignatureActiveParameter = { fg = c.corona, bold = true },
    LspCodeLens = { fg = c.muted, italic = true },
    LspCodeLensSeparator = { fg = c.subtle },
    LspInlayHint = { fg = c.muted, bg = c.surface0, italic = true },
    LspInfoBorder = { link = "FloatBorder" },
  }

  apply_groups(groups)

  -- Link Tree-sitter captures to the base syntax groups.
  local links = {
    ["@origin.choice"] = "OriginChoice",
    ["@origin.escape"] = "OriginFlow",
    ["@origin.structure"] = "OriginStructure",
    ["@origin.type.marker"] = "Type",
    ["@variable"] = "Identifier",
    ["@variable.builtin"] = "Special",
    ["@variable.parameter"] = "Identifier",
    ["@variable.parameter.builtin"] = "Special",
    ["@variable.member"] = "Identifier",
    ["@constant"] = "Constant",
    ["@constant.builtin"] = "Constant",
    ["@constant.macro"] = "OriginMeta",
    ["@module"] = "Identifier",
    ["@module.builtin"] = "Special",
    ["@label"] = "OriginChoice",
    ["@string"] = "String",
    ["@string.documentation"] = "String",
    ["@string.regexp"] = "Special",
    ["@string.escape"] = "SpecialChar",
    ["@string.special"] = "String",
    ["@string.special.symbol"] = "String",
    ["@string.special.path"] = "Underlined",
    ["@string.special.url"] = "Underlined",
    ["@character"] = "Character",
    ["@character.special"] = "SpecialChar",
    ["@boolean"] = "Boolean",
    ["@number"] = "Number",
    ["@number.float"] = "Float",
    ["@type"] = "Type",
    ["@type.builtin"] = "Type",
    ["@type.definition"] = "OriginTypeDefinition",
    ["@attribute"] = "OriginMeta",
    ["@attribute.builtin"] = "OriginMeta",
    ["@property"] = "Identifier",
    ["@function"] = "OriginDefinition",
    ["@function.builtin"] = "OriginCall",
    ["@function.call"] = "OriginCall",
    ["@function.macro"] = "OriginMeta",
    ["@function.method"] = "OriginDefinition",
    ["@function.method.call"] = "OriginCall",
    ["@constructor"] = "Type",
    ["@operator"] = "Operator",
    ["@keyword"] = "Keyword",
    ["@keyword.coroutine"] = "OriginFlow",
    ["@keyword.function"] = "OriginStructure",
    ["@keyword.operator"] = "Keyword",
    ["@keyword.import"] = "OriginMeta",
    ["@keyword.type"] = "Type",
    ["@keyword.modifier"] = "Keyword",
    ["@keyword.repeat"] = "Repeat",
    ["@keyword.return"] = "OriginFlow",
    ["@keyword.debug"] = "Debug",
    ["@keyword.exception"] = "OriginChoice",
    ["@keyword.conditional"] = "Conditional",
    ["@keyword.conditional.ternary"] = "Conditional",
    ["@keyword.directive"] = "PreProc",
    ["@keyword.directive.define"] = "Define",
    ["@punctuation.delimiter"] = "Delimiter",
    ["@punctuation.bracket"] = "Delimiter",
    ["@punctuation.special"] = "Special",
    ["@comment"] = "Comment",
    ["@comment.documentation"] = "Comment",
    ["@comment.error"] = "DiagnosticError",
    ["@comment.warning"] = "DiagnosticWarn",
    ["@comment.todo"] = "Todo",
    ["@comment.note"] = "DiagnosticInfo",
    ["@markup.strong"] = "Bold",
    ["@markup.italic"] = "Italic",
    ["@markup.strikethrough"] = "DiagnosticDeprecated",
    ["@markup.underline"] = "Underlined",
    ["@markup.heading"] = "Title",
    ["@markup.heading.1"] = "Title",
    ["@markup.heading.2"] = "Title",
    ["@markup.heading.3"] = "Bold",
    ["@markup.heading.4"] = "Bold",
    ["@markup.quote"] = "Comment",
    ["@markup.math"] = "Special",
    ["@markup.link"] = "Underlined",
    ["@markup.link.label"] = "Special",
    ["@markup.link.url"] = "Underlined",
    ["@markup.raw"] = "String",
    ["@markup.raw.block"] = "String",
    ["@markup.list"] = "Special",
    ["@markup.list.checked"] = "DiagnosticOk",
    ["@markup.list.unchecked"] = "DiagnosticHint",
    ["@diff.plus"] = "Added",
    ["@diff.minus"] = "Removed",
    ["@diff.delta"] = "Changed",
    ["@tag"] = "Tag",
    ["@tag.builtin"] = "Tag",
    ["@tag.attribute"] = "Identifier",
    ["@tag.delimiter"] = "Delimiter",

    -- Older capture names retained for Neovim/parser compatibility.
    ["@parameter"] = "Identifier",
    ["@field"] = "Identifier",
    ["@method"] = "OriginDefinition",
    ["@method.call"] = "OriginCall",
    ["@conditional"] = "Conditional",
    ["@repeat"] = "Repeat",
    ["@exception"] = "Exception",
    ["@include"] = "Include",
    ["@text"] = "Normal",
    ["@text.strong"] = "Bold",
    ["@text.emphasis"] = "Italic",
    ["@text.underline"] = "Underlined",
    ["@text.title"] = "Title",
    ["@text.uri"] = "Underlined",
    ["@text.todo"] = "Todo",
  }

  apply_groups(vim.tbl_map(function(link)
    return { link = link }
  end, links))

  -- LSP semantic token mappings.
  apply_groups({
    ["@lsp.type.class"] = { link = "Type" },
    ["@lsp.type.decorator"] = { link = "OriginMeta" },
    ["@lsp.type.enum"] = { link = "Type" },
    ["@lsp.type.enumMember"] = { link = "Constant" },
    ["@lsp.type.event"] = { link = "Special" },
    ["@lsp.type.function"] = { link = "OriginCall" },
    ["@lsp.type.interface"] = { link = "Type" },
    ["@lsp.type.lifetime"] = { link = "OriginMetaType" },
    ["@lsp.type.macro"] = { link = "OriginMeta" },
    ["@lsp.type.method"] = { link = "OriginCall" },
    ["@lsp.type.namespace"] = { link = "Identifier" },
    ["@lsp.type.number"] = { link = "Number" },
    ["@lsp.type.operator"] = { link = "Operator" },
    ["@lsp.type.parameter"] = { link = "Identifier" },
    ["@lsp.type.property"] = { link = "Identifier" },
    ["@lsp.type.regexp"] = { link = "Special" },
    ["@lsp.type.string"] = { link = "String" },
    ["@lsp.type.struct"] = { link = "Type" },
    ["@lsp.type.type"] = { link = "Type" },
    ["@lsp.type.typeParameter"] = { link = "OriginMetaType" },
    ["@lsp.type.variable"] = { link = "Identifier" },
    ["@lsp.mod.defaultLibrary"] = {},

    ["@lsp.typemod.function.declaration"] = { link = "OriginDefinition" },
    ["@lsp.typemod.function.definition"] = { link = "OriginDefinition" },
    ["@lsp.typemod.method.declaration"] = { link = "OriginDefinition" },
    ["@lsp.typemod.method.definition"] = { link = "OriginDefinition" },
    ["@lsp.typemod.class.declaration"] = { link = "OriginTypeDefinition" },
    ["@lsp.typemod.class.definition"] = { link = "OriginTypeDefinition" },
    ["@lsp.typemod.struct.declaration"] = { link = "OriginTypeDefinition" },
    ["@lsp.typemod.struct.definition"] = { link = "OriginTypeDefinition" },
    ["@lsp.typemod.enum.declaration"] = { link = "OriginTypeDefinition" },
    ["@lsp.typemod.enum.definition"] = { link = "OriginTypeDefinition" },
    ["@lsp.typemod.interface.declaration"] = { link = "OriginTypeDefinition" },
    ["@lsp.typemod.interface.definition"] = { link = "OriginTypeDefinition" },
    ["@lsp.typemod.type.declaration"] = { link = "OriginTypeDefinition" },
    ["@lsp.typemod.type.definition"] = { link = "OriginTypeDefinition" },
    ["@lsp.typemod.namespace.declaration"] = { link = "OriginDefinition" },
    ["@lsp.typemod.namespace.definition"] = { link = "OriginDefinition" },
    ["@lsp.typemod.variable.declaration"] = { link = "OriginDeclaration" },
    ["@lsp.typemod.variable.definition"] = { link = "OriginDeclaration" },
    ["@lsp.typemod.property.declaration"] = { link = "OriginDeclaration" },
    ["@lsp.typemod.property.definition"] = { link = "OriginDeclaration" },
  })

  if config.terminal_colors then
    apply_terminal(c)
  end
end

return M
