local M = {}

local function apply_groups(groups)
  for group, spec in pairs(groups) do
    vim.api.nvim_set_hl(0, group, spec)
  end
end

local function clear_neutral_backgrounds(groups, c)
  local neutral = {
    [c.bg] = true,
    [c.surface0] = true,
    [c.surface1] = true,
    [c.surface2] = true,
  }

  for _, spec in pairs(groups) do
    if neutral[spec.bg] then
      spec.bg = "NONE"
    end
  end
end

function M.apply(c, config)
  local groups = {
    -- Telescope ------------------------------------------------------------
    TelescopeNormal = { fg = c.fg, bg = c.surface1 },
    TelescopeBorder = { fg = c.border, bg = c.surface1 },
    TelescopePromptNormal = { fg = c.fg, bg = c.surface2 },
    TelescopePromptBorder = { fg = c.border, bg = c.surface2 },
    TelescopePromptTitle = { fg = c.void, bg = c.starlight, bold = true },
    TelescopePreviewTitle = { fg = c.fg, bg = c.surface1, bold = true },
    TelescopeResultsTitle = { fg = c.muted, bg = c.surface1, bold = true },
    TelescopeSelection = { bg = c.selection, bold = true },
    TelescopeSelectionCaret = { fg = c.starlight, bg = c.selection },
    TelescopeMatching = { fg = c.corona, bold = true, underline = true },
    TelescopeMultiSelection = { fg = c.blueshift },

    -- fzf-lua --------------------------------------------------------------
    FzfLuaNormal = { fg = c.fg, bg = c.surface1 },
    FzfLuaBorder = { fg = c.border, bg = c.surface1 },
    FzfLuaTitle = { fg = c.void, bg = c.starlight, bold = true },
    FzfLuaCursor = { fg = c.void, bg = c.starlight },
    FzfLuaCursorLine = { bg = c.selection, bold = true },
    FzfLuaSearch = { fg = c.corona, bold = true },
    FzfLuaHeaderText = { fg = c.fg, bold = true },
    FzfLuaHeaderBind = { fg = c.muted },
    FzfLuaPathColNr = { fg = c.subtle },
    FzfLuaPathLineNr = { fg = c.muted },

    -- snacks.nvim ---------------------------------------------------------
    SnacksNormal = { fg = c.fg, bg = c.bg },
    SnacksNormalNC = { fg = c.fg, bg = c.surface1 },
    SnacksWinBar = { fg = c.fg, bold = true },
    SnacksWinBarNC = { fg = c.muted },
    SnacksBackdrop = { bg = c.void, blend = 55 },
    SnacksPicker = { fg = c.fg, bg = c.surface1 },
    SnacksPickerBorder = { fg = c.border, bg = c.surface1 },
    SnacksPickerInputBorder = { fg = c.border, bg = c.surface2 },
    SnacksPickerInputTitle = { fg = c.void, bg = c.starlight, bold = true },
    SnacksPickerListTitle = { fg = c.fg, bg = c.surface1, bold = true },
    SnacksPickerPreviewTitle = { fg = c.fg, bg = c.surface1, bold = true },
    SnacksPickerListCursorLine = { bg = c.selection, bold = true },
    SnacksPickerPreviewCursorLine = { bg = c.surface2 },
    SnacksPickerSelected = { fg = c.fg, bold = true },
    SnacksPickerMatch = { fg = c.corona, bold = true, underline = true },
    SnacksPickerPrompt = { fg = c.starlight, bold = true },
    SnacksPickerDir = { fg = c.muted },
    SnacksPickerPathHidden = { fg = c.subtle },
    SnacksPickerPathIgnored = { fg = c.subtle },
    SnacksIndent = { fg = c.subtle },
    SnacksIndentScope = { fg = c.muted },
    SnacksDashboardHeader = { fg = c.starlight, bold = true },
    SnacksDashboardKey = { fg = c.starlight, bold = true },
    SnacksDashboardDesc = { fg = c.fg },
    SnacksDashboardIcon = { fg = c.muted },
    SnacksDashboardFooter = { fg = c.muted, italic = true },
    SnacksNotifierBorderError = { fg = c.redshift },
    SnacksNotifierBorderWarn = { fg = c.corona },
    SnacksNotifierBorderInfo = { fg = c.blueshift },
    SnacksNotifierBorderDebug = { fg = c.muted },
    SnacksNotifierBorderTrace = { fg = c.subtle },

    -- Completion: nvim-cmp and blink.cmp ----------------------------------
    CmpItemAbbr = { fg = c.fg },
    CmpItemAbbrMatch = { fg = c.corona, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.corona, bold = true },
    CmpItemAbbrDeprecated = { fg = c.muted, strikethrough = true },
    CmpItemKind = { fg = c.muted },
    CmpItemMenu = { fg = c.muted, italic = true },
    BlinkCmpMenu = { fg = c.fg, bg = c.surface1 },
    BlinkCmpMenuBorder = { fg = c.border, bg = c.surface1 },
    BlinkCmpMenuSelection = { fg = c.void, bg = c.starlight, bold = true },
    BlinkCmpLabel = { fg = c.fg },
    BlinkCmpLabelMatch = { fg = c.corona, bold = true },
    BlinkCmpLabelDeprecated = { fg = c.muted, strikethrough = true },
    BlinkCmpKind = { fg = c.muted },
    BlinkCmpSource = { fg = c.muted, italic = true },
    BlinkCmpGhostText = { fg = c.subtle, italic = true },
    BlinkCmpDoc = { fg = c.fg, bg = c.surface1 },
    BlinkCmpDocBorder = { fg = c.border, bg = c.surface1 },
    BlinkCmpDocSeparator = { fg = c.border },
    BlinkCmpSignatureHelp = { fg = c.fg, bg = c.surface1 },
    BlinkCmpSignatureHelpBorder = { fg = c.border, bg = c.surface1 },
    BlinkCmpSignatureHelpActiveParameter = { fg = c.corona, bold = true },

    -- Git ------------------------------------------------------------------
    GitSignsAdd = { fg = c.aurora },
    GitSignsChange = { fg = c.corona },
    GitSignsDelete = { fg = c.redshift },
    GitSignsChangedelete = { fg = c.redshift },
    GitSignsTopdelete = { fg = c.redshift },
    GitSignsUntracked = { fg = c.aurora },
    GitSignsCurrentLineBlame = { fg = c.muted, italic = true },
    GitSignsAddPreview = { fg = c.aurora, bg = c.diff_add },
    GitSignsDeletePreview = { fg = c.redshift, bg = c.diff_delete },
    GitSignsAddInline = { bg = c.diff_add },
    GitSignsChangeInline = { bg = c.diff_change },
    GitSignsDeleteInline = { bg = c.diff_delete },
    FugitiveHeader = { fg = c.fg, bold = true },
    FugitiveHeading = { fg = c.fg, bold = true },
    NeogitBranch = { fg = c.fg, bold = true },
    NeogitRemote = { fg = c.muted },
    NeogitHunkHeader = { fg = c.fg, bg = c.surface1 },
    NeogitHunkHeaderHighlight = { fg = c.starlight, bg = c.surface2, bold = true },
    NeogitDiffAdd = { fg = c.aurora, bg = c.diff_add },
    NeogitDiffDelete = { fg = c.redshift, bg = c.diff_delete },
    DiffviewFilePanelTitle = { fg = c.fg, bold = true },
    DiffviewFilePanelCounter = { fg = c.muted },
    DiffviewFilePanelFileName = { fg = c.fg },
    DiffviewStatusAdded = { fg = c.aurora },
    DiffviewStatusModified = { fg = c.corona },
    DiffviewStatusDeleted = { fg = c.redshift },
    DiffviewCursorLine = { bg = c.surface1 },
    GitConflictCurrent = { bg = c.diff_add },
    GitConflictIncoming = { bg = c.diff_change },
    GitConflictAncestor = { bg = c.surface2 },

    -- File explorers -------------------------------------------------------
    NeoTreeNormal = { fg = c.fg, bg = c.bg },
    NeoTreeNormalNC = { fg = c.fg, bg = c.bg },
    NeoTreeFloatNormal = { fg = c.fg, bg = c.surface1 },
    NeoTreeFloatBorder = { fg = c.border, bg = c.surface1 },
    NeoTreeDirectoryName = { fg = c.fg, bold = true },
    NeoTreeDirectoryIcon = { fg = c.muted },
    NeoTreeRootName = { fg = c.starlight, bold = true },
    NeoTreeFileName = { fg = c.fg },
    NeoTreeFileNameOpened = { fg = c.starlight, bold = true },
    NeoTreeDimText = { fg = c.subtle },
    NeoTreeIndentMarker = { fg = c.subtle },
    NeoTreeExpander = { fg = c.muted },
    NeoTreeGitAdded = { fg = c.aurora },
    NeoTreeGitModified = { fg = c.corona },
    NeoTreeGitDeleted = { fg = c.redshift },
    NeoTreeGitUntracked = { fg = c.aurora },
    NvimTreeNormal = { fg = c.fg, bg = c.bg },
    NvimTreeNormalNC = { fg = c.fg, bg = c.bg },
    NvimTreeRootFolder = { fg = c.starlight, bold = true },
    NvimTreeFolderName = { fg = c.fg, bold = true },
    NvimTreeOpenedFolderName = { fg = c.starlight, bold = true },
    NvimTreeFolderIcon = { fg = c.muted },
    NvimTreeIndentMarker = { fg = c.subtle },
    NvimTreeGitNew = { fg = c.aurora },
    NvimTreeGitDirty = { fg = c.corona },
    NvimTreeGitDeleted = { fg = c.redshift },
    OilDir = { fg = c.fg, bold = true },
    OilDirIcon = { fg = c.muted },
    OilLink = { fg = c.fg, underline = true },
    OilLinkTarget = { fg = c.muted, italic = true },
    OilHidden = { fg = c.subtle },
    OilCreate = { fg = c.aurora },
    OilChange = { fg = c.corona },
    OilDelete = { fg = c.redshift },
    OilMove = { fg = c.corona },
    OilCopy = { fg = c.aurora },

    -- Navigation and UI ----------------------------------------------------
    WhichKeyNormal = { fg = c.fg, bg = c.surface1 },
    WhichKeyBorder = { fg = c.border, bg = c.surface1 },
    WhichKeyTitle = { fg = c.void, bg = c.starlight, bold = true },
    WhichKey = { fg = c.starlight, bold = true },
    WhichKeyGroup = { fg = c.fg, bold = true },
    WhichKeyDesc = { fg = c.fg },
    WhichKeySeparator = { fg = c.subtle },
    WhichKeyValue = { fg = c.muted },
    LazyNormal = { fg = c.fg, bg = c.surface1 },
    LazyButton = { fg = c.fg, bg = c.surface2 },
    LazyButtonActive = { fg = c.void, bg = c.starlight, bold = true },
    LazyH1 = { fg = c.void, bg = c.starlight, bold = true },
    LazyH2 = { fg = c.fg, bold = true },
    LazySpecial = { fg = c.muted },
    LazyReasonPlugin = { fg = c.fg },
    MasonNormal = { fg = c.fg, bg = c.surface1 },
    MasonHeader = { fg = c.void, bg = c.starlight, bold = true },
    MasonHeaderSecondary = { fg = c.void, bg = c.ash, bold = true },
    MasonHighlight = { fg = c.fg, bold = true },
    MasonHighlightBlock = { fg = c.void, bg = c.starlight },
    MasonMuted = { fg = c.muted },
    MasonMutedBlock = { fg = c.muted, bg = c.surface2 },

    BufferLineFill = { bg = c.surface0 },
    BufferLineBackground = { fg = c.muted, bg = c.surface0 },
    BufferLineBufferSelected = { fg = c.starlight, bg = c.bg, bold = true },
    BufferLineBufferVisible = { fg = c.fg, bg = c.surface1 },
    BufferLineSeparator = { fg = c.border, bg = c.surface0 },
    BufferLineSeparatorSelected = { fg = c.border, bg = c.bg },
    BufferLineIndicatorSelected = { fg = c.starlight, bg = c.bg },
    BufferLineModified = { fg = c.corona, bg = c.surface0 },
    BufferLineModifiedSelected = { fg = c.corona, bg = c.bg },
    BufferLineDuplicate = { fg = c.subtle, bg = c.surface0, italic = true },
    BufferLineError = { fg = c.redshift, bg = c.surface0 },
    BufferLineWarning = { fg = c.corona, bg = c.surface0 },
    BufferLineInfo = { fg = c.blueshift, bg = c.surface0 },

    -- Notifications and command UI ----------------------------------------
    NoiceCmdline = { fg = c.fg },
    NoiceCmdlineIcon = { fg = c.starlight },
    NoiceCmdlinePopup = { fg = c.fg, bg = c.surface1 },
    NoiceCmdlinePopupBorder = { fg = c.border, bg = c.surface1 },
    NoiceCmdlinePopupTitle = { fg = c.starlight, bold = true },
    NoiceConfirm = { fg = c.fg, bg = c.surface1 },
    NoiceConfirmBorder = { fg = c.border, bg = c.surface1 },
    NoiceFormatTitle = { fg = c.starlight, bold = true },
    NotifyERRORBorder = { fg = c.redshift },
    NotifyERRORTitle = { fg = c.redshift, bold = true },
    NotifyERRORIcon = { fg = c.redshift },
    NotifyWARNBorder = { fg = c.corona },
    NotifyWARNTitle = { fg = c.corona, bold = true },
    NotifyWARNIcon = { fg = c.corona },
    NotifyINFOBorder = { fg = c.blueshift },
    NotifyINFOTitle = { fg = c.blueshift, bold = true },
    NotifyINFOIcon = { fg = c.blueshift },
    NotifyDEBUGBorder = { fg = c.muted },
    NotifyDEBUGTitle = { fg = c.muted, bold = true },
    NotifyDEBUGIcon = { fg = c.muted },
    NotifyTRACEBorder = { fg = c.subtle },
    NotifyTRACETitle = { fg = c.muted },
    NotifyTRACEIcon = { fg = c.muted },
    FidgetTitle = { fg = c.fg, bold = true },
    FidgetTask = { fg = c.muted, italic = true },

    -- Indentation and context ---------------------------------------------
    IblIndent = { fg = c.subtle },
    IblWhitespace = { fg = c.subtle },
    IblScope = { fg = c.muted },
    IndentBlanklineChar = { fg = c.subtle },
    IndentBlanklineContextChar = { fg = c.muted },
    TreesitterContext = { bg = c.surface0 },
    TreesitterContextLineNumber = { fg = c.muted, bg = c.surface0 },
    TreesitterContextBottom = { underline = true, sp = c.border },
    IlluminatedWordText = { bg = c.surface2 },
    IlluminatedWordRead = { bg = c.surface2 },
    IlluminatedWordWrite = { bg = c.selection, underline = true },
    MiniIndentscopeSymbol = { fg = c.muted },

    -- Trouble and TODO comments -------------------------------------------
    TroubleNormal = { fg = c.fg, bg = c.bg },
    TroubleNormalNC = { fg = c.fg, bg = c.bg },
    TroubleText = { fg = c.fg },
    TroubleCount = { fg = c.void, bg = c.starlight, bold = true },
    TroubleCode = { fg = c.muted },
    TroubleSource = { fg = c.muted, italic = true },
    TroubleIndent = { fg = c.subtle },
    TroubleFoldIcon = { fg = c.muted },
    TroubleFilename = { fg = c.fg, bold = true },
    TodoBgTODO = { fg = c.void, bg = c.starlight, bold = true },
    TodoFgTODO = { fg = c.starlight, bold = true },
    TodoSignTODO = { fg = c.starlight },
    TodoBgFIX = { fg = c.void, bg = c.redshift, bold = true },
    TodoFgFIX = { fg = c.redshift, bold = true },
    TodoSignFIX = { fg = c.redshift },
    TodoBgWARN = { fg = c.void, bg = c.corona, bold = true },
    TodoFgWARN = { fg = c.corona, bold = true },
    TodoSignWARN = { fg = c.corona },
    TodoBgINFO = { fg = c.void, bg = c.blueshift, bold = true },
    TodoFgINFO = { fg = c.blueshift, bold = true },
    TodoSignINFO = { fg = c.blueshift },
    TodoBgNOTE = { fg = c.void, bg = c.ash, bold = true },
    TodoFgNOTE = { fg = c.muted, bold = true },
    TodoSignNOTE = { fg = c.muted },

    -- Motion ---------------------------------------------------------------
    FlashLabel = { fg = c.void, bg = c.corona, bold = true },
    FlashMatch = { fg = c.corona, underline = true },
    FlashCurrent = { fg = c.void, bg = c.starlight, bold = true },
    FlashBackdrop = { fg = c.subtle },
    LeapMatch = { fg = c.void, bg = c.corona, bold = true },
    LeapLabelPrimary = { fg = c.void, bg = c.starlight, bold = true },
    LeapLabelSecondary = { fg = c.void, bg = c.ash, bold = true },
    LeapBackdrop = { fg = c.subtle },

    -- Markdown -------------------------------------------------------------
    RenderMarkdownH1 = { fg = c.starlight, bold = true },
    RenderMarkdownH2 = { fg = c.starlight, bold = true },
    RenderMarkdownH3 = { fg = c.fg, bold = true },
    RenderMarkdownH4 = { fg = c.fg, bold = true },
    RenderMarkdownCode = { bg = c.surface1 },
    RenderMarkdownCodeInline = { bg = c.surface1 },
    RenderMarkdownBullet = { fg = c.muted },
    RenderMarkdownDash = { fg = c.border },
    RenderMarkdownTableHead = { fg = c.fg, bold = true },
    RenderMarkdownTableRow = { fg = c.fg },
    RenderMarkdownSuccess = { fg = c.aurora },
    RenderMarkdownInfo = { fg = c.blueshift },
    RenderMarkdownHint = { fg = c.muted },
    RenderMarkdownWarn = { fg = c.corona },
    RenderMarkdownError = { fg = c.redshift },

    -- DAP ------------------------------------------------------------------
    DapBreakpoint = { fg = c.redshift },
    DapBreakpointCondition = { fg = c.corona },
    DapBreakpointRejected = { fg = c.muted },
    DapLogPoint = { fg = c.blueshift },
    DapStopped = { fg = c.corona, bg = c.diff_change },
    DapUIVariable = { fg = c.fg },
    DapUIScope = { fg = c.fg, bold = true },
    DapUIType = { fg = c.blueshift },
    DapUIValue = { fg = c.fg },
    DapUIModifiedValue = { fg = c.corona, bold = true },
    DapUIDecoration = { fg = c.muted },
    DapUIThread = { fg = c.blueshift },
    DapUIStoppedThread = { fg = c.corona },
    DapUIWatchesError = { fg = c.redshift },
    DapUIWatchesValue = { fg = c.blueshift },
    DapUIBreakpointsCurrentLine = { fg = c.corona, bold = true },

    -- Symbols, breadcrumbs, and outlines ----------------------------------
    NavicIconsFile = { fg = c.muted },
    NavicIconsModule = { fg = c.muted },
    NavicIconsNamespace = { fg = c.muted },
    NavicIconsClass = { fg = c.muted },
    NavicIconsMethod = { fg = c.muted },
    NavicIconsProperty = { fg = c.muted },
    NavicIconsField = { fg = c.muted },
    NavicIconsConstructor = { fg = c.muted },
    NavicIconsEnum = { fg = c.muted },
    NavicIconsInterface = { fg = c.muted },
    NavicIconsFunction = { fg = c.muted },
    NavicIconsVariable = { fg = c.muted },
    NavicText = { fg = c.fg },
    NavicSeparator = { fg = c.subtle },
    AerialNormal = { fg = c.fg, bg = c.bg },
    AerialGuide = { fg = c.subtle },
    AerialLine = { bg = c.selection, bold = true },
    AerialLineNC = { bg = c.surface1 },
    AerialFunctionIcon = { fg = c.muted },
    AerialClassIcon = { fg = c.muted },
    AerialStructIcon = { fg = c.muted },
    AerialInterfaceIcon = { fg = c.muted },
    DropBarCurrentContext = { fg = c.fg, bold = true },
    DropBarCurrentContextIcon = { fg = c.muted },
    DropBarIconKindDefault = { fg = c.muted },
    DropBarMenuCurrentContext = { bg = c.selection, bold = true },
    DropBarMenuHoverEntry = { bg = c.surface2 },

    -- Dashboard ------------------------------------------------------------
    AlphaHeader = { fg = c.starlight, bold = true },
    AlphaButtons = { fg = c.fg },
    AlphaShortcut = { fg = c.starlight, bold = true },
    AlphaFooter = { fg = c.muted, italic = true },
    DashboardHeader = { fg = c.starlight, bold = true },
    DashboardCenter = { fg = c.fg },
    DashboardShortCut = { fg = c.starlight, bold = true },
    DashboardFooter = { fg = c.muted, italic = true },

    -- mini.nvim ------------------------------------------------------------
    MiniIconsAzure = { fg = c.muted },
    MiniIconsBlue = { fg = c.muted },
    MiniIconsCyan = { fg = c.muted },
    MiniIconsGreen = { fg = c.muted },
    MiniIconsGrey = { fg = c.muted },
    MiniIconsOrange = { fg = c.muted },
    MiniIconsPurple = { fg = c.muted },
    MiniIconsRed = { fg = c.muted },
    MiniIconsYellow = { fg = c.muted },
    DevIconDefault = { fg = c.muted },
    MiniCursorword = { bg = c.surface2 },
    MiniCursorwordCurrent = { bg = c.surface2 },
    MiniJump = { fg = c.void, bg = c.corona, bold = true },
    MiniJump2dSpot = { fg = c.void, bg = c.starlight, bold = true },
    MiniPickMatchCurrent = { bg = c.selection, bold = true },
    MiniPickMatchMarked = { fg = c.blueshift },
    MiniPickMatchRanges = { fg = c.corona, bold = true },
    MiniPickPrompt = { fg = c.starlight, bold = true },
    MiniStatuslineModeNormal = { fg = c.void, bg = c.starlight, bold = true },
    MiniStatuslineModeInsert = { fg = c.void, bg = c.starlight, bold = true },
    MiniStatuslineModeVisual = { fg = c.void, bg = c.ash, bold = true },
    MiniStatuslineModeReplace = { fg = c.void, bg = c.redshift, bold = true },
    MiniStatuslineModeCommand = { fg = c.void, bg = c.starlight, bold = true },
    MiniStatuslineDevinfo = { fg = c.fg, bg = c.surface2 },
    MiniStatuslineFilename = { fg = c.muted, bg = c.surface1 },
    MiniStatuslineFileinfo = { fg = c.fg, bg = c.surface2 },
    MiniTablineCurrent = { fg = c.starlight, bg = c.bg, bold = true },
    MiniTablineVisible = { fg = c.fg, bg = c.surface1 },
    MiniTablineHidden = { fg = c.muted, bg = c.surface0 },
    MiniDiffSignAdd = { fg = c.aurora },
    MiniDiffSignChange = { fg = c.corona },
    MiniDiffSignDelete = { fg = c.redshift },

    -- AI assistants --------------------------------------------------------
    CopilotSuggestion = { fg = c.subtle, italic = true },
    CopilotAnnotation = { fg = c.muted, italic = true },
    AvanteTitle = { fg = c.void, bg = c.starlight, bold = true },
    AvanteReversedTitle = { fg = c.starlight },
    AvanteSubtitle = { fg = c.void, bg = c.ash, bold = true },
    AvanteReversedSubtitle = { fg = c.ash },
    AvanteThirdTitle = { fg = c.fg, bold = true },
    AvanteReversedThirdTitle = { fg = c.muted },
    AvanteConflictCurrent = { bg = c.diff_add },
    AvanteConflictIncoming = { bg = c.diff_change },
    AvanteInlineHint = { fg = c.muted, italic = true },
    CodeCompanionChatHeader = { fg = c.starlight, bold = true },
    CodeCompanionChatSeparator = { fg = c.border },
    CodeCompanionChatTokens = { fg = c.muted },
    CodeCompanionChatTool = { fg = c.corona, bold = true },
    CodeCompanionVirtualText = { fg = c.muted, italic = true },
  }

  if config.transparent then
    clear_neutral_backgrounds(groups, c)
  end
  apply_groups(groups)

  -- Use one color for all completion kinds.
  local kinds = {
    "Text",
    "Method",
    "Function",
    "Constructor",
    "Field",
    "Variable",
    "Class",
    "Interface",
    "Module",
    "Property",
    "Unit",
    "Value",
    "Enum",
    "Keyword",
    "Snippet",
    "Color",
    "File",
    "Reference",
    "Folder",
    "EnumMember",
    "Constant",
    "Struct",
    "Event",
    "Operator",
    "TypeParameter",
  }
  for _, kind in ipairs(kinds) do
    vim.api.nvim_set_hl(0, "CmpItemKind" .. kind, { fg = c.muted })
    vim.api.nvim_set_hl(0, "BlinkCmpKind" .. kind, { fg = c.muted })
  end

  -- Alternate neutral shades for rainbow delimiter groups.
  for index, color in ipairs({ c.starlight, c.ash, c.fg, c.muted, c.starlight, c.ash, c.fg }) do
    vim.api.nvim_set_hl(
      0,
      "RainbowDelimiter"
        .. ({ "Red", "Yellow", "Blue", "Orange", "Green", "Violet", "Cyan" })[index],
      { fg = color }
    )
  end
end

return M
